version: "3.8"

services:
  demo-night-app-redis:
    image: redis
    ports:
      - "6379:6379"

  demo-night-app-serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: localhost_test_token
      SRH_CONNECTION_STRING: "redis://demo-night-app-redis:6379" # Using `demo-night-app-redis` hostname since they're in the same Docker network.

  demo-night-app-postgres:
    image: postgres
    environment:
      POSTGRES_DB: demo-night-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
